version: '3'

services:
  social_media_postgresql:
    image: postgres:15
    container_name: social_media_postgresql
    volumes:
      - social_media_postgresql:/var/lib/social_media_postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - social_media_network

volumes:
  social_media_postgresql:
    external: true

networks:
  social_media_network:
    external: true